"""Objects generated by the simulator; none can reach a trading gateway."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional, Tuple


class CycleState(str, Enum):
    IDLE = "IDLE"
    CANDIDATE_DETECTED = "CANDIDATE_DETECTED"
    PRE_TRADE_CHECK = "PRE_TRADE_CHECK"
    RESOURCES_RESERVED = "RESOURCES_RESERVED"
    LEGS_SUBMITTED = "LEGS_SUBMITTED"
    FULLY_FILLED = "FULLY_FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    REJECTED = "REJECTED"
    ABORT_AND_UNWIND = "ABORT_AND_UNWIND"
    PRIMARY_MARKET_SUBMITTED = "PRIMARY_MARKET_SUBMITTED"
    PRIMARY_MARKET_CONFIRMED = "PRIMARY_MARKET_CONFIRMED"
    PRIMARY_MARKET_REJECTED = "PRIMARY_MARKET_REJECTED"
    INVENTORY_RECONCILED = "INVENTORY_RECONCILED"
    CLOSED = "CLOSED"
    DATA_INVALID = "DATA_INVALID"
    KILL_SWITCH = "KILL_SWITCH"


@dataclass(frozen=True)
class SimulatedOrder:
    order_id: str
    cycle_id: str
    symbol: str
    side: str
    quantity: float
    order_type: str
    submit_time: datetime
    simulated_only: bool = True


@dataclass(frozen=True)
class SimulatedFill:
    fill_id: str
    order_id: str
    cycle_id: str
    symbol: str
    side: str
    quantity: float
    average_price: float
    total_value: float
    fill_time: datetime
    levels_consumed: int


@dataclass(frozen=True)
class PaperTradeCycle:
    cycle_id: str
    direction: str
    decision_time: datetime
    fill_time: Optional[datetime]
    state: CycleState
    state_history: Tuple[str, ...]
    orders: Tuple[SimulatedOrder, ...]
    fills: Tuple[SimulatedFill, ...]
    primary_request_id: Optional[str]
    snapshot_profit: float
    execution_profit: float
    final_pnl: float
    rejection_reason: Optional[str]
    execution_risk_label: str
